### ISSUE TITLE
running python python_wizard.py error

### ISSUE THREAD

**Issue by deladriere** [ptwz/python_wizard#1]
I am trying to run `python python_wizard.py -f arduino fired.wav`
but I get this error :

Traceback (most recent call last):
  File "python_wizard.py", line 60, in <module>
    settings.import_from_argparse(args)
  File "/Users/***/Downloads/python_wizard-master/backend.py", line 37, in import_from_argparse
    self.import_from_dict(v)
  File "/Users/***/Downloads/python_wizard-master/backend.py", line 46, in import_from_dict
    self.__setattr__(key, type(self.__getattribute__(key))(input_dict[key]))
AttributeError: 'userSettings' object has no attribute 'filename'

I am on Mac with Python 2.7.11

**Comment by ptwz** [comment]
Please try out the current version in the "cleanup" branch. I think https://github.com/ptwz/python_wizard/commit/d19d9222084fcf27c6a36dbc1ce06ea8bbb5964e#diff-5dc1d54bad9108be9983760850ad96a3 did the trick..
