### ISSUE TITLE
Improve message for stereo / multiple channels not supported

### ISSUE THREAD

**Issue by kevinjwalters** [ptwz/python_wizard#10]
It's not obvious what's going on with the current version if you accidentally feed it a stereo wave file:

``` 
Traceback (most recent call last):
  File "/path/venv/bin/python_wizard", line 71, in <module>
    b=Buffer.fromWave(args.filename)
  File "/path/venv/lib/python3.X/site-packages/pywizard/Buffer.py", line 32, in fromWave
    assert(max(d2) <= 1)
```

This issue may help others who search for what this output means.

**Comment by kevinjwalters** [comment]
Thanks for the fix, all python wizards will be most pleased.
