### ISSUE TITLE
Please help! 

### ISSUE THREAD

**Issue by ilaws** [ptwz/python_wizard#18]
When i try to run i get this error;
NameError: name 'CodingTable' is not defined 
 or longer version.
(work) C:\dev\python_wizard>python python_wizard -f arduino a.wav
C:\dev\python_wizard\pywizard\Reflector.py:53: RuntimeWarning: invalid value encountered in double_scalars
  k[1] = -r[1] / r[0]
Traceback (most recent call last):
  File "C:\dev\python_wizard\python_wizard", line 87, in <module>
    result = BitPacker.pack(x)
  File "C:\dev\python_wizard\pywizard\FrameDataBinaryEncoder.py", line 18, in pack
    parametersList = [ x.parameters() for x in frameData ]
  File "C:\dev\python_wizard\pywizard\FrameDataBinaryEncoder.py", line 18, in <listcomp>
    parametersList = [ x.parameters() for x in frameData ]
  File "C:\dev\python_wizard\pywizard\FrameData.py", line 37, in parameters
    self._parameters = self.parametersWithTranslate(False)
  File "C:\dev\python_wizard\pywizard\FrameData.py", line 47, in parametersWithTranslate
    parameters["kParameterGain"] = self.parameterizedValueForRMS(self.reflector.rms, translate=translate)
  File "C:\dev\python_wizard\pywizard\Reflector.py", line 76, in rms
    return self.codingTable.rms[CodingTable.kStopFrameIndex - 1]
NameError: name 'CodingTable' is not defined

**Comment by christurnerchris** [comment]
download thonny python for what ever operating system you have  add the scipy package , then open the gui file and run it
