### ISSUE TITLE
Crash when converting a specific wav file. 

### ISSUE THREAD

**Issue by krperry** [ptwz/python_wizard#21]
I was converting my own numbers from 0 to 9.  I know they already exist it was just a test.  All converted but the number nine. I will try to attach it here but first here is the error I got:

Before the error I just tried to attach the wav file and it would not let me.  Here is a drop box link to it:
https://www.dropbox.com/scl/fi/po3fjhaz8o53109iprrhn/Nine.wav?rlkey=fzpojpkuvc55ftupp92xe304n&dl=0

After you try it I will remove the link kbut for now it will be up there. 

Note I tried this with python 3.11 and 3.8.9
I would rather not go back to 2.x if I don't need to.
Traceback (most recent call last):
  File "C:\data\python_wizard\python_wizard", line 87, in <module>
    result = BitPacker.pack(x)
  File "C:\data\python_wizard\pywizard\FrameDataBinaryEncoder.py", line 18, in pack
    parametersList = [ x.parameters() for x in frameData ]
  File "C:\data\python_wizard\pywizard\FrameDataBinaryEncoder.py", line 18, in <listcomp>
    parametersList = [ x.parameters() for x in frameData ]
  File "C:\data\python_wizard\pywizard\FrameData.py", line 37, in parameters
    self._parameters = self.parametersWithTranslate(False)
  File "C:\data\python_wizard\pywizard\FrameData.py", line 47, in parametersWithTranslate
    parameters["kParameterGain"] = self.parameterizedValueForRMS(self.reflector.rms, translate=translate)
  File "C:\data\python_wizard\pywizard\Reflector.py", line 76, in rms
    return self.codingTable.rms[CodingTable.kStopFrameIndex - 1]
NameError: name 'CodingTable' is not defined

**Comment by krperry** [comment]
I should mention I used this as a command:
python python_wizard my.wav -f arduino -S -p > my.h
