### ISSUE TITLE
Quick Guide

### ISSUE THREAD

**Issue by Yanvps01** [ptwz/python_wizard#22]
Hi, can you make a quick guide on how to execute this files for noobs?

Edit: I downloaded thonny python and added the scipy package, then runned the file python_wizard_gui ( as said by christurnerchris in the issue #18). But still i can't convert the .wav files to LPC streams.

I got this error message in Thonny:

>>> %Run python_wizard_gui
0 1.1538461538461537
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\yanvp\AppData\Roaming\Python\Python310\site-packages\scipy\__init__.py", line 150, in __getattr__
    return globals()[name]
KeyError: 'array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yanvp\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\yanvp\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\Users\yanvp\Desktop\python_wizard-master\python_wizard_gui", line 304, in _repeatedly
    b = Buffer.fromWave(self.filename)
  File "C:\Users\yanvp\Desktop\python_wizard-master\pywizard\Buffer.py", line 31, in fromWave
    d2 = sp.array(data, 'float')
  File "C:\Users\yanvp\AppData\Roaming\Python\Python310\site-packages\scipy\__init__.py", line 152, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'array'

This is my UI:

![image](https://github.com/ptwz/python_wizard/assets/137127208/efd7bc62-d630-4107-b7e6-7fa8d299d2dc)

This is the file I want to convert:

https://drive.google.com/drive/folders/1eITYrZ8G5vy2q2sdLpcDv9ZlD8DFJGni?usp=drive_link

**Comment by sintech** [comment]
Wav file should be MONO, 8000 Hz, 16-bit PCM.
Use "Normalize" filter to enhance coding results.

**Comment by Yanvps01** [comment]
> Wav file should be MONO, 8000 Hz, 16-bit PCM. Use "Normalize" filter to enhance coding results.

Yes, the .WAV file is exactly like that. But still can't get results. Can you make another file available so I can test it out?

**Comment by federicochiesa** [comment]
The problem is that scipy in the latest version removed many deprecated methods. You need to install an older version of scipy to make the program work.

**Comment by ptwz** [comment]
I'll push an updated version for use with newer scipy versions.

**Comment by christurnerchris** [comment]
I have same problem, similar errors.  How fo you get an old scipy?

**Comment by ptwz** [comment]
Should be fixed in [add73eb](https://github.com/ptwz/python_wizard/commit/add73ebf3c8fed306225dffd2e0229aee1a38e8f)
